import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/components/header/Header";
import styles from "../styles/Home.module.scss";
import { Shape } from "@/components/shape/Shape";
import Image from "next/image";
import ilustration from '../images/illustration-devices.svg'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
        </style>
      </Head>
      <main className={styles.main}>
        <Shape />
        <Header />
        <Image alt="feature" src={ilustration} className={styles.ilustration} />
      </main>
    </>
  );
}
