import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/components/header/Header";
import styles from "../styles/Home.module.scss";
import { Shape } from "@/components/shape/Shape";
import Image from "next/image";
import ilustration from "../images/illustration-devices.svg";
import { Details } from "@/components/details/Details";
import { Menu } from "@/components/menu/Menu";
import { useState } from "react";

export default function Home() {
  const [showMenu, setShowMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Project Tracking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        {showMenu && <Menu />}
        <Shape />
        <Header showMenu={showMenu} setShowMenu={setShowMenu} />
        <Image alt="feature" src={ilustration} className={styles.ilustration} />
        <Details />
      </main>
    </>
  );
}
